### PR TITLE
add basic data loading pic with Common Lisp in Emacs

### PR DESCRIPTION
**Pull request by ak-coram**

### CODE REVIEW

**Comment by RandomFractals** [comment]
@ak-coram that looks really good. Could you add a script, if there is any to the `/scripts` folder?

That's where I've been trying to put all the REPL scripts for now.

**Comment by RandomFractals** [comment]
Also, can you adjust your lisp script to load data from the `../data/crimes.csv` as I have it in other Jupyter notebook samples and interactive scripts for vscode? 

I still have to add better instructions about changing the downloaded `CSV` to just `crimes.csv`, but looks like you were able to follow my docs re. download and placement of that raw CSV data to work in this open data project repo so far.

**Comment by ak-coram** [comment]
@RandomFractals Sorry, but the bindings are still pretty unfinished and I'm just starting to figure out what the API should look like: such a script is probably not going to be runnable for very long (I don't think makes much sense to add it at this point). I'm also fine with not merging this until the API is more stable if you prefer.

**Comment by RandomFractals** [comment]
I liked the pic. How about we open a ticket describing where you at with this Lisp binding, add the cli pic you shared and merge for others to look forward to when you finalize it?

**Comment by RandomFractals** [comment]
stictly for our notes, I got it from your duckdb discord share in their show-and-tell channel:

https://discord.com/channels/909674491309850675/1009741727600484382/1030514383585030185

I do think this is awesome! and will excite some devs using Lisp and Emacs to check out your repo too.

Alpha v. repo: https://github.com/ak-coram/cl-duckdb

chicago-crimes-duckdb-in-lisp

**Pull request merged**
